"""rename address

Revision ID: 57003eaa90af
Revises: c1c781951d2c
Create Date: 2025-06-17 21:37:10.274335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57003eaa90af'
down_revision = 'c1c781951d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###